### ISSUE TITLE
不同类别节点展示不同信息

### ISSUE THREAD

**Issue by yuehuazhiqi** [bluejoe2008/InteractiveGraph-neo4j#15]
您好，可以在visNodeProperty.info中加入if判断吗，根据不同的节点类别显示不同的信息。我尝试了很多种形式的条件判断，都没有作用。或者我可以在哪里修改来实现这种功能。

**Comment by HC-teemo** [comment]
You can refer to the `visNodeProperty.info` in [this article](https://www.jianshu.com/p/4c0f798e16b7) (line 2-5):
```
<p align=center>
#if($prop.image) 
  <img width=150 src="${prop.image}"><br> 
#end 
  <b>${prop.name}</b>
</p>
<p align=left>
  <ul>
    <li>评分:${node.rate}</li>
    <li>类型:${node.category}</li>
    <li>时长:${node.length}分钟</li>
    <li>语言:${node.language}</li>
  </ul>
</p>
```

**Comment by yuehuazhiqi** [comment]
我把#号删去之后，似乎无法识别这种写法，会把if($prop.image)和end显示在展示界面中（我是在最新版的edge浏览器中测试的）
![捕获](https://user-images.githubusercontent.com/60464638/148735829-58cb6fc3-aa19-49b5-8e88-fd05aff05d86.PNG)

**Comment by HC-teemo** [comment]
The `#` is part of the syntax and cannot be deleted.


> 我把#号删去之后，似乎无法识别这种写法，会把if($prop.image)和end显示在展示界面中（我是在最新版的edge浏览器中测试的） ![捕获](https://user-images.githubusercontent.com/60464638/148735829-58cb6fc3-aa19-49b5-8e88-fd05aff05d86.PNG)

**Comment by yuehuazhiqi** [comment]
谢谢您的帮助
